"""refunds

Revision ID: 030be91fb05a
Revises: 78b2e367aa9c
Create Date: 2026-08-17 00:27:14.173098

"""
# Modernised from Alembic's stock template so generated revisions are already
# ruff-clean: PEP 604 unions and collections.abc.Sequence instead of
# typing.Union / typing.Sequence. Without this, every new revision would
# reintroduce UP006/UP007/UP035 violations and lint would drift into being
# ignored.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '030be91fb05a'
down_revision: str | Sequence[str] | None = '78b2e367aa9c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('amount_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('destination', sa.String(length=12), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('razorpay_refund_id', sa.String(length=64), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_created_at'), 'refunds', ['created_at'], unique=False)
    op.create_index(op.f('ix_refunds_idempotency_key'), 'refunds', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_refunds_legacy_id'), 'refunds', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refunds_public_id'), 'refunds', ['public_id'], unique=True)
    op.create_index(op.f('ix_refunds_razorpay_refund_id'), 'refunds', ['razorpay_refund_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_razorpay_refund_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_public_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_legacy_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_idempotency_key'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_created_at'), table_name='refunds')
    op.drop_table('refunds')
    # ### end Alembic commands ###
