"""billing

Revision ID: 06e5466679de
Revises: 413f94b6e1e1
Create Date: 2026-08-15 22:30:14.649956

"""
# Modernised from Alembic's stock template so generated revisions are already
# ruff-clean: PEP 604 unions and collections.abc.Sequence instead of
# typing.Union / typing.Sequence. Without this, every new revision would
# reintroduce UP006/UP007/UP035 violations and lint would drift into being
# ignored.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '06e5466679de'
down_revision: str | Sequence[str] | None = '413f94b6e1e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_kiosks', sa.Integer(), server_default='1', nullable=False),
    sa.Column('price_floor_bw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_ceiling_bw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_floor_color', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_ceiling_color', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plans_legacy_id'), 'plans', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_plans_public_id'), 'plans', ['public_id'], unique=True)
    op.create_table('owner_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'duration_months', name='uq_owner_duration')
    )
    op.create_index(op.f('ix_owner_discounts_user_id'), 'owner_discounts', ['user_id'], unique=False)
    op.create_table('plan_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'duration_months', name='uq_plan_duration')
    )
    op.create_index(op.f('ix_plan_discounts_legacy_id'), 'plan_discounts', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_plan_discounts_plan_id'), 'plan_discounts', ['plan_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending_payment', nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('monthly_price_charged', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('negotiated_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('free_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_payment_id')
    )
    op.create_index(op.f('ix_subscriptions_expires_at'), 'subscriptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_legacy_id'), 'subscriptions', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_public_id'), 'subscriptions', ['public_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_public_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_legacy_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_expires_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_plan_discounts_plan_id'), table_name='plan_discounts')
    op.drop_index(op.f('ix_plan_discounts_legacy_id'), table_name='plan_discounts')
    op.drop_table('plan_discounts')
    op.drop_index(op.f('ix_owner_discounts_user_id'), table_name='owner_discounts')
    op.drop_table('owner_discounts')
    op.drop_index(op.f('ix_plans_public_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_legacy_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
