"""printing

Revision ID: 08712b07a60f
Revises: 06e5466679de
Create Date: 2026-08-16 11:53:42.621466

"""
# Modernised from Alembic's stock template so generated revisions are already
# ruff-clean: PEP 604 unions and collections.abc.Sequence instead of
# typing.Union / typing.Sequence. Without this, every new revision would
# reintroduce UP006/UP007/UP035 violations and lint would drift into being
# ignored.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '08712b07a60f'
down_revision: str | Sequence[str] | None = '06e5466679de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=400), nullable=False),
    sa.Column('original_path', sa.String(length=600), nullable=True),
    sa.Column('normalised_path', sa.String(length=600), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=16), server_default='uploaded', nullable=False),
    sa.Column('rejection_reason', sa.String(length=300), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_legacy_id'), 'documents', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_documents_public_id'), 'documents', ['public_id'], unique=True)
    op.create_index(op.f('ix_documents_state'), 'documents', ['state'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('print_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('kiosk_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('colour', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('duplex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('copies', sa.Integer(), server_default='1', nullable=False),
    sa.Column('page_range', sa.String(length=200), nullable=True),
    sa.Column('predicted_sheets', sa.Integer(), nullable=False),
    sa.Column('actual_sheets', sa.Integer(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_tasks_created_at'), 'print_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_print_tasks_document_id'), 'print_tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_print_tasks_kiosk_id'), 'print_tasks', ['kiosk_id'], unique=False)
    op.create_index(op.f('ix_print_tasks_lease_expires_at'), 'print_tasks', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_print_tasks_legacy_id'), 'print_tasks', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_print_tasks_public_id'), 'print_tasks', ['public_id'], unique=True)
    op.create_index('ix_print_tasks_queue', 'print_tasks', ['kiosk_id', 'state', 'position', 'created_at'], unique=False)
    op.create_index(op.f('ix_print_tasks_state'), 'print_tasks', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_print_tasks_state'), table_name='print_tasks')
    op.drop_index('ix_print_tasks_queue', table_name='print_tasks')
    op.drop_index(op.f('ix_print_tasks_public_id'), table_name='print_tasks')
    op.drop_index(op.f('ix_print_tasks_legacy_id'), table_name='print_tasks')
    op.drop_index(op.f('ix_print_tasks_lease_expires_at'), table_name='print_tasks')
    op.drop_index(op.f('ix_print_tasks_kiosk_id'), table_name='print_tasks')
    op.drop_index(op.f('ix_print_tasks_document_id'), table_name='print_tasks')
    op.drop_index(op.f('ix_print_tasks_created_at'), table_name='print_tasks')
    op.drop_table('print_tasks')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_state'), table_name='documents')
    op.drop_index(op.f('ix_documents_public_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_legacy_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
