"""device enrolments

Revision ID: 4ca9150b1ea0
Revises: 08712b07a60f
Create Date: 2026-08-16 13:52:14.014888

"""
# Modernised from Alembic's stock template so generated revisions are already
# ruff-clean: PEP 604 unions and collections.abc.Sequence instead of
# typing.Union / typing.Sequence. Without this, every new revision would
# reintroduce UP006/UP007/UP035 violations and lint would drift into being
# ignored.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4ca9150b1ea0'
down_revision: str | Sequence[str] | None = '08712b07a60f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_enrolments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kiosk_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_enrolments_code_hash'), 'device_enrolments', ['code_hash'], unique=True)
    op.create_index(op.f('ix_device_enrolments_kiosk_id'), 'device_enrolments', ['kiosk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_enrolments_kiosk_id'), table_name='device_enrolments')
    op.drop_index(op.f('ix_device_enrolments_code_hash'), table_name='device_enrolments')
    op.drop_table('device_enrolments')
    # ### end Alembic commands ###
