"""wallet payments

Revision ID: 5bc3d4fb6418
Revises: 030be91fb05a
Create Date: 2026-08-21 00:55:22.439961

"""
# Modernised from Alembic's stock template so generated revisions are already
# ruff-clean: PEP 604 unions and collections.abc.Sequence instead of
# typing.Union / typing.Sequence. Without this, every new revision would
# reintroduce UP006/UP007/UP035 violations and lint would drift into being
# ignored.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5bc3d4fb6418'
down_revision: str | Sequence[str] | None = '030be91fb05a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """A wallet payment is a Payment, and `gateway` was the wrong name for it.

    Written by hand rather than autogenerated. Alembic sees a dropped `gateway`
    and an added `source` and would emit exactly that -- which throws away the
    value on every existing row. This renames, so a payment that recorded
    "owner_gateway" six months ago still says so afterwards, and a refund still
    knows which account it must go back to.
    """
    op.alter_column("payments", "gateway", new_column_name="source")
    op.create_index(op.f("ix_payments_source"), "payments", ["source"], unique=False)

    # Null for wallet payments: nothing was opened at a gateway. The unique
    # index stays -- Postgres allows many NULLs under one -- so two gateway rows
    # still cannot claim the same Razorpay order.
    op.alter_column(
        "payments",
        "razorpay_order_id",
        existing_type=sa.String(length=64),
        nullable=True,
    )


def downgrade() -> None:
    """Undo both, and refuse rather than lose money.

    A wallet payment has no `razorpay_order_id` and no `gateway` this schema can
    express, so restoring NOT NULL with such rows present would either fail on
    the constraint or, with a filled-in default, silently claim a Razorpay order
    that does not exist. Better to stop and make the operator decide.
    """
    stranded = (
        op.get_bind()
        .execute(
            sa.text("select count(*) from payments where razorpay_order_id is null")
        )
        .scalar_one()
    )
    if stranded:
        raise RuntimeError(
            f"{stranded} wallet payment(s) have no razorpay_order_id. "
            "Downgrading would have to invent one. Decide what happens to them "
            "first -- this migration will not guess."
        )

    op.alter_column(
        "payments",
        "razorpay_order_id",
        existing_type=sa.String(length=64),
        nullable=False,
    )
    op.drop_index(op.f("ix_payments_source"), table_name="payments")
    op.alter_column("payments", "source", new_column_name="gateway")
