"""kiosk favourites

Revision ID: 777766be9bfe
Revises: 9a1c4d77e2b1
Create Date: 2026-08-23 15:02:42.296455

"""
# Modernised from Alembic's stock template so generated revisions are already
# ruff-clean: PEP 604 unions and collections.abc.Sequence instead of
# typing.Union / typing.Sequence. Without this, every new revision would
# reintroduce UP006/UP007/UP035 violations and lint would drift into being
# ignored.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '777766be9bfe'
down_revision: str | Sequence[str] | None = '9a1c4d77e2b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiosk_favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kiosk_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kiosk_id', name='uq_favourite_user_kiosk')
    )
    op.create_index(op.f('ix_kiosk_favourites_kiosk_id'), 'kiosk_favourites', ['kiosk_id'], unique=False)
    op.create_index(op.f('ix_kiosk_favourites_user_id'), 'kiosk_favourites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kiosk_favourites_user_id'), table_name='kiosk_favourites')
    op.drop_index(op.f('ix_kiosk_favourites_kiosk_id'), table_name='kiosk_favourites')
    op.drop_table('kiosk_favourites')
    # ### end Alembic commands ###
