"""payments and razorpay webhooks

Revision ID: 78b2e367aa9c
Revises: 7b6a82cf9cf5
Create Date: 2026-08-16 23:41:12.737532

"""
# Modernised from Alembic's stock template so generated revisions are already
# ruff-clean: PEP 604 unions and collections.abc.Sequence instead of
# typing.Union / typing.Sequence. Without this, every new revision would
# reintroduce UP006/UP007/UP035 violations and lint would drift into being
# ignored.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '78b2e367aa9c'
down_revision: str | Sequence[str] | None = '7b6a82cf9cf5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('kiosk_id', sa.Integer(), nullable=True),
    sa.Column('gateway', sa.String(length=20), nullable=False),
    sa.Column('collecting_user_id', sa.Integer(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('amount_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refunded_inr', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='created', nullable=False),
    sa.Column('failure_reason', sa.String(length=300), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collecting_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_collecting_user_id'), 'payments', ['collecting_user_id'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_kind'), 'payments', ['kind'], unique=False)
    op.create_index(op.f('ix_payments_kiosk_id'), 'payments', ['kiosk_id'], unique=False)
    op.create_index(op.f('ix_payments_legacy_id'), 'payments', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_public_id'), 'payments', ['public_id'], unique=True)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.add_column('kiosk_payment_configs', sa.Column('razorpay_webhook_secret_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kiosk_payment_configs', 'razorpay_webhook_secret_encrypted')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_public_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_legacy_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_kiosk_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_kind'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_collecting_user_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
