"""wallet

Revision ID: 7b6a82cf9cf5
Revises: 80b1d7388f0d
Create Date: 2026-08-16 19:08:41.394998

"""
# Modernised from Alembic's stock template so generated revisions are already
# ruff-clean: PEP 604 unions and collections.abc.Sequence instead of
# typing.Union / typing.Sequence. Without this, every new revision would
# reintroduce UP006/UP007/UP035 violations and lint would drift into being
# ignored.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7b6a82cf9cf5'
down_revision: str | Sequence[str] | None = '80b1d7388f0d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance_inr', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_legacy_id'), 'wallets', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.create_table('wallet_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'reference', name='uq_wallet_entry_reference')
    )
    op.create_index(op.f('ix_wallet_entries_created_at'), 'wallet_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_wallet_entries_kind'), 'wallet_entries', ['kind'], unique=False)
    op.create_index(op.f('ix_wallet_entries_legacy_id'), 'wallet_entries', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_wallet_entries_public_id'), 'wallet_entries', ['public_id'], unique=True)
    op.create_index(op.f('ix_wallet_entries_wallet_id'), 'wallet_entries', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_entries_wallet_id'), table_name='wallet_entries')
    op.drop_index(op.f('ix_wallet_entries_public_id'), table_name='wallet_entries')
    op.drop_index(op.f('ix_wallet_entries_legacy_id'), table_name='wallet_entries')
    op.drop_index(op.f('ix_wallet_entries_kind'), table_name='wallet_entries')
    op.drop_index(op.f('ix_wallet_entries_created_at'), table_name='wallet_entries')
    op.drop_table('wallet_entries')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_legacy_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
