"""orders

Revision ID: 80b1d7388f0d
Revises: 4ca9150b1ea0
Create Date: 2026-08-16 18:46:00.989353

"""
# Modernised from Alembic's stock template so generated revisions are already
# ruff-clean: PEP 604 unions and collections.abc.Sequence instead of
# typing.Union / typing.Sequence. Without this, every new revision would
# reintroduce UP006/UP007/UP035 violations and lint would drift into being
# ignored.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '80b1d7388f0d'
down_revision: str | Sequence[str] | None = '4ca9150b1ea0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kiosk_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('subtotal_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fee_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=12), nullable=True),
    sa.Column('gateway', sa.String(length=20), nullable=True),
    sa.Column('payment_reference', sa.String(length=80), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_expires_at'), 'orders', ['expires_at'], unique=False)
    op.create_index(op.f('ix_orders_kiosk_id'), 'orders', ['kiosk_id'], unique=False)
    op.create_index('ix_orders_kiosk_state', 'orders', ['kiosk_id', 'state'], unique=False)
    op.create_index(op.f('ix_orders_legacy_id'), 'orders', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_orders_payment_reference'), 'orders', ['payment_reference'], unique=True)
    op.create_index(op.f('ix_orders_public_id'), 'orders', ['public_id'], unique=True)
    op.create_index(op.f('ix_orders_state'), 'orders', ['state'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index('ix_orders_user_recent', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('kind', sa.String(length=16), server_default='document', nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('colour', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('duplex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('copies', sa.Integer(), server_default='1', nullable=False),
    sa.Column('page_range', sa.String(length=200), nullable=True),
    sa.Column('page_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('impressions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sheets', sa.Integer(), server_default='0', nullable=False),
    sa.Column('amount_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_document_id'), 'order_items', ['document_id'], unique=False)
    op.create_index(op.f('ix_order_items_legacy_id'), 'order_items', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_legacy_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_document_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_orders_user_recent', table_name='orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_state'), table_name='orders')
    op.drop_index(op.f('ix_orders_public_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_reference'), table_name='orders')
    op.drop_index(op.f('ix_orders_legacy_id'), table_name='orders')
    op.drop_index('ix_orders_kiosk_state', table_name='orders')
    op.drop_index(op.f('ix_orders_kiosk_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_expires_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
