"""payment config change requests get a public id

Revision ID: 9a1c4d77e2b1
Revises: 713f62ab6a78
Create Date: 2026-08-21 12:10:00.000000

"""
# Modernised from Alembic's stock template so generated revisions are already
# ruff-clean: PEP 604 unions and collections.abc.Sequence instead of
# typing.Union / typing.Sequence. Without this, every new revision would
# reintroduce UP006/UP007/UP035 violations and lint would drift into being
# ignored.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.ids import IdPrefix, new_id

# revision identifiers, used by Alembic.
revision: str = '9a1c4d77e2b1'
down_revision: str | Sequence[str] | None = '713f62ab6a78'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """An id an admin route can address a request by.

    Hand-written rather than autogenerated because of the backfill. Added
    nullable, filled row by row -- each id must be distinct, so a single UPDATE
    with one generated value would violate the unique index it is about to
    get -- and only then made NOT NULL. Adding it NOT NULL in one step fails
    against any table that already has rows.
    """
    op.add_column(
        "payment_config_change_requests",
        sa.Column("public_id", sa.String(length=24), nullable=True),
    )

    connection = op.get_bind()
    existing = connection.execute(
        sa.text("select id from payment_config_change_requests where public_id is null")
    ).scalars().all()
    for row_id in existing:
        connection.execute(
            sa.text(
                "update payment_config_change_requests set public_id = :pid "
                "where id = :id"
            ),
            {"pid": new_id(IdPrefix.PAYMENT_CONFIG_CHANGE), "id": row_id},
        )

    op.alter_column(
        "payment_config_change_requests", "public_id", nullable=False
    )
    op.create_index(
        op.f("ix_payment_config_change_requests_public_id"),
        "payment_config_change_requests",
        ["public_id"],
        unique=True,
    )


def downgrade() -> None:
    op.drop_index(
        op.f("ix_payment_config_change_requests_public_id"),
        table_name="payment_config_change_requests",
    )
    op.drop_column("payment_config_change_requests", "public_id")
