"""kiosks

Revision ID: c7afb2634a04
Revises: 85a75727c039
Create Date: 2026-08-15 11:36:22.953491

"""
# Modernised from Alembic's stock template so generated revisions are already
# ruff-clean: PEP 604 unions and collections.abc.Sequence instead of
# typing.Union / typing.Sequence. Without this, every new revision would
# reintroduce UP006/UP007/UP035 violations and lint would drift into being
# ignored.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c7afb2634a04'
down_revision: str | Sequence[str] | None = '85a75727c039'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiosks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kiosk_type', sa.String(length=20), server_default='platform', nullable=False),
    sa.Column('onboarding_stage', sa.String(length=24), server_default='registered', nullable=False),
    sa.Column('onboarding_note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('accepts_wallet', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('location_description', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price_bw_single', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_bw_double', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_color_single', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_color_double', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiosks_legacy_id'), 'kiosks', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_kiosks_name'), 'kiosks', ['name'], unique=True)
    op.create_index(op.f('ix_kiosks_onboarding_stage'), 'kiosks', ['onboarding_stage'], unique=False)
    op.create_index(op.f('ix_kiosks_public_id'), 'kiosks', ['public_id'], unique=True)
    op.create_table('kiosk_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kiosk_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kiosk_id', 'user_id', 'role', name='uq_kiosk_user_role')
    )
    op.create_index(op.f('ix_kiosk_assignments_kiosk_id'), 'kiosk_assignments', ['kiosk_id'], unique=False)
    op.create_index(op.f('ix_kiosk_assignments_role'), 'kiosk_assignments', ['role'], unique=False)
    op.create_index(op.f('ix_kiosk_assignments_user_id'), 'kiosk_assignments', ['user_id'], unique=False)
    op.create_table('kiosk_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('kiosk_id', sa.Integer(), nullable=False),
    sa.Column('device_key', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='offline', nullable=False),
    sa.Column('capabilities', sa.Text(), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('agent_update_status', sa.String(length=32), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiosk_devices_device_key'), 'kiosk_devices', ['device_key'], unique=True)
    op.create_index(op.f('ix_kiosk_devices_kiosk_id'), 'kiosk_devices', ['kiosk_id'], unique=True)
    op.create_index(op.f('ix_kiosk_devices_legacy_id'), 'kiosk_devices', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_kiosk_devices_public_id'), 'kiosk_devices', ['public_id'], unique=True)
    op.create_index(op.f('ix_kiosk_devices_token_hash'), 'kiosk_devices', ['token_hash'], unique=False)
    op.create_table('kiosk_paper',
    sa.Column('kiosk_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='250', nullable=False),
    sa.Column('used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('warning_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_warning_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kiosk_id')
    )
    op.create_table('paper_refill_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kiosk_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('sheets_added', sa.Integer(), nullable=False),
    sa.Column('capacity_at_change', sa.Integer(), nullable=False),
    sa.Column('used_before_change', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_refill_logs_created_at'), 'paper_refill_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_refill_logs_kiosk_id'), 'paper_refill_logs', ['kiosk_id'], unique=False)
    op.create_index(op.f('ix_paper_refill_logs_legacy_id'), 'paper_refill_logs', ['legacy_id'], unique=False)
    op.create_table('staff_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kiosk_id', sa.Integer(), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_invites_email'), 'staff_invites', ['email'], unique=False)
    op.create_index(op.f('ix_staff_invites_kiosk_id'), 'staff_invites', ['kiosk_id'], unique=False)
    op.create_index(op.f('ix_staff_invites_token_hash'), 'staff_invites', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_invites_token_hash'), table_name='staff_invites')
    op.drop_index(op.f('ix_staff_invites_kiosk_id'), table_name='staff_invites')
    op.drop_index(op.f('ix_staff_invites_email'), table_name='staff_invites')
    op.drop_table('staff_invites')
    op.drop_index(op.f('ix_paper_refill_logs_legacy_id'), table_name='paper_refill_logs')
    op.drop_index(op.f('ix_paper_refill_logs_kiosk_id'), table_name='paper_refill_logs')
    op.drop_index(op.f('ix_paper_refill_logs_created_at'), table_name='paper_refill_logs')
    op.drop_table('paper_refill_logs')
    op.drop_table('kiosk_paper')
    op.drop_index(op.f('ix_kiosk_devices_token_hash'), table_name='kiosk_devices')
    op.drop_index(op.f('ix_kiosk_devices_public_id'), table_name='kiosk_devices')
    op.drop_index(op.f('ix_kiosk_devices_legacy_id'), table_name='kiosk_devices')
    op.drop_index(op.f('ix_kiosk_devices_kiosk_id'), table_name='kiosk_devices')
    op.drop_index(op.f('ix_kiosk_devices_device_key'), table_name='kiosk_devices')
    op.drop_table('kiosk_devices')
    op.drop_index(op.f('ix_kiosk_assignments_user_id'), table_name='kiosk_assignments')
    op.drop_index(op.f('ix_kiosk_assignments_role'), table_name='kiosk_assignments')
    op.drop_index(op.f('ix_kiosk_assignments_kiosk_id'), table_name='kiosk_assignments')
    op.drop_table('kiosk_assignments')
    op.drop_index(op.f('ix_kiosks_public_id'), table_name='kiosks')
    op.drop_index(op.f('ix_kiosks_onboarding_stage'), table_name='kiosks')
    op.drop_index(op.f('ix_kiosks_name'), table_name='kiosks')
    op.drop_index(op.f('ix_kiosks_legacy_id'), table_name='kiosks')
    op.drop_table('kiosks')
    # ### end Alembic commands ###
