"""payment configs

Revision ID: e2bb42908221
Revises: cab66c1f140d
Create Date: 2026-08-15 21:59:29.653509

"""
# Modernised from Alembic's stock template so generated revisions are already
# ruff-clean: PEP 604 unions and collections.abc.Sequence instead of
# typing.Union / typing.Sequence. Without this, every new revision would
# reintroduce UP006/UP007/UP035 violations and lint would drift into being
# ignored.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e2bb42908221'
down_revision: str | Sequence[str] | None = 'cab66c1f140d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiosk_payment_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('razorpay_key_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_key_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('is_configured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('configured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiosk_payment_configs_legacy_id'), 'kiosk_payment_configs', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_kiosk_payment_configs_user_id'), 'kiosk_payment_configs', ['user_id'], unique=True)
    op.create_table('payment_config_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('proof_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_config_change_requests_legacy_id'), 'payment_config_change_requests', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_payment_config_change_requests_status'), 'payment_config_change_requests', ['status'], unique=False)
    op.create_index(op.f('ix_payment_config_change_requests_user_id'), 'payment_config_change_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_config_change_requests_user_id'), table_name='payment_config_change_requests')
    op.drop_index(op.f('ix_payment_config_change_requests_status'), table_name='payment_config_change_requests')
    op.drop_index(op.f('ix_payment_config_change_requests_legacy_id'), table_name='payment_config_change_requests')
    op.drop_table('payment_config_change_requests')
    op.drop_index(op.f('ix_kiosk_payment_configs_user_id'), table_name='kiosk_payment_configs')
    op.drop_index(op.f('ix_kiosk_payment_configs_legacy_id'), table_name='kiosk_payment_configs')
    op.drop_table('kiosk_payment_configs')
    # ### end Alembic commands ###
