"""Where uploaded files live.

Two things the backend being replaced got wrong, both fixed here by making them
impossible rather than by remembering:

* **Names collided.** Files were named from a second-resolution timestamp, so a
  student uploading three PDFs in one batch had three rows pointing at one file
  on disk. Names here carry a uuid4.
* **A filename was almost a path.** The user-supplied filename reached the
  filesystem with only a `Path(...).name` between it and the disk, at one call
  site out of several. Here the caller never chooses a path: it hands over bytes
  and gets back an opaque *key*, and only `path()` turns a key into a location,
  refusing anything that leaves the root.

A key is relative on purpose -- the storage root is a deploy setting, and a
database full of absolute paths cannot be moved to another machine. The
migration relies on this too: legacy rows carry their own relative paths and
resolve through the same function.
"""

from datetime import UTC, datetime
from enum import StrEnum
from pathlib import Path, PurePosixPath
from uuid import uuid4

from app.core.config import get_settings

# Long enough for ".pdf"/".jpeg" and anything else we accept.
MAX_SUFFIX_LENGTH = 12


class StorageArea(StrEnum):
    """Top-level directory. Separate areas so retention can treat them
    differently -- an original may be purged while its normalised copy is still
    being printed, or the other way round."""

    ORIGINAL = "originals"
    NORMALISED = "normalised"


class InvalidStorageKey(ValueError):
    """A key that does not name a file inside the storage root.

    Not an `AppError`: keys are generated by this module, never by a client, so
    reaching here means a bug or a tampered database row. Both should stop dead
    rather than quietly read a file from somewhere else on the disk.
    """


def _safe_suffix(filename: str | None) -> str:
    """Reduce a user-supplied filename to a safe `.ext`, or nothing at all.

    The alnum filter is the guard, and it is the whole guard. Whatever the
    filename claims to be, only letters and digits survive into the key, so no
    separator, dot-dot or drive letter can reach the filesystem by this route.
    That matters most for a name like `report.pd\\..\\..\\evil`: POSIX path
    parsing treats the backslashes as ordinary characters and hands back the
    lot as a "suffix", which on a Windows host would be a climb.

    Splitting the path first, as an earlier draft did, looks protective and
    changes nothing -- `.suffix` already takes the last component. Deliberately
    breaking it failed no test, which is how that was found.
    """
    if not filename:
        return ""
    ext = "".join(ch for ch in PurePosixPath(filename).suffix if ch.isalnum())
    return ("." + ext)[:MAX_SUFFIX_LENGTH] if ext else ""


class DocumentStore:
    """Bytes in, opaque key out."""

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root)

    @classmethod
    def from_settings(cls) -> "DocumentStore":
        return cls(get_settings().STORAGE_ROOT)

    # ── keys ────────────────────────────────────────────────────────────────

    def new_key(
        self,
        area: StorageArea,
        *,
        user_id: int,
        filename: str | None = None,
        now: datetime | None = None,
    ) -> str:
        """A key nothing else will ever be given.

        Sharded by month because a single directory holding every upload the
        platform has ever taken becomes slow to list long before it becomes
        large, and the first person to notice is whoever is trying to diagnose
        something at 2am.
        """
        now = now or datetime.now(UTC)
        return (
            f"{area.value}/{now:%Y/%m}/"
            f"usr{user_id}_{uuid4().hex}{_safe_suffix(filename)}"
        )

    def path(self, key: str) -> Path:
        """Resolve a key to a location inside the root, or refuse.

        The check is on the *resolved* path rather than on the text of the key,
        so a climb assembled out of legitimate-looking segments is caught just
        as a literal `..` is.
        """
        if not key or not key.strip():
            raise InvalidStorageKey("Empty storage key.")

        candidate = PurePosixPath(key.replace("\\", "/"))
        if candidate.is_absolute():
            raise InvalidStorageKey(f"Storage key must be relative: {key!r}")

        root = self.root.resolve()
        resolved = (root / candidate).resolve()
        if not resolved.is_relative_to(root):
            raise InvalidStorageKey(f"Storage key escapes the storage root: {key!r}")
        return resolved

    # ── reading and writing ─────────────────────────────────────────────────

    def write(self, key: str, data: bytes) -> None:
        target = self.path(key)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)

    def save(
        self,
        area: StorageArea,
        *,
        user_id: int,
        filename: str | None,
        data: bytes,
        now: datetime | None = None,
    ) -> str:
        key = self.new_key(area, user_id=user_id, filename=filename, now=now)
        self.write(key, data)
        return key

    def read(self, key: str) -> bytes:
        return self.path(key).read_bytes()

    def exists(self, key: str) -> bool:
        return self.path(key).is_file()

    def size(self, key: str) -> int | None:
        """Bytes on disk, or None when there is no file.

        None rather than 0, because zero is a real size and "no file" is a
        different fact -- conflating them is how a purged document reports as a
        successfully stored empty one.
        """
        try:
            return self.path(key).stat().st_size
        except (OSError, InvalidStorageKey):
            return None

    def delete(self, key: str) -> bool:
        """Remove the file. True if it was there, False if it already was not.

        Never raises on a missing file: retention sweeps the same rows
        repeatedly, and a file someone removed by hand must not stop the sweep
        for everything behind it.
        """
        try:
            self.path(key).unlink()
            return True
        except FileNotFoundError:
            return False
